### PR TITLE
eip-140: Add a paragraph about the return data of REVERT

### PR DESCRIPTION
**Pull request by pirapira**
Fell free to rephrase.

### CODE REVIEW

**Comment by pirapira** [comment]
@axic any comments?

**Comment by axic** [comment]
> The `REVERT` instruction during contract creation does not deploy the contents of the memory region, but reveals the contents through the proposed [RETURNDATACOPY/SIZE instructions]().

This needs the EIP number and if this is added, the header should include the "depends on" field. Also this should need an actual test added with bytecode.

**Comment by axic** [comment]
Well it seems this was already changed by the EIP editors so closing this here.

**Comment by pirapira** [comment]
@axic I agree.

**Pull request closed without merging**
